steps: 
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lstm-442003/lstm', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lstm-442003/lstm']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'lstm', '--image', 'gcr.io/lstm-442003/lstm', '--region', 'us-central1', '--platform', 'managed','--port','8080']
images:
- gcr.io/lstm-442003/lstm

options:
  logging: CLOUD_LOGGING_ONLY